id: IA6E894EA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T15:00:34+00:00'
last_modified: '2022-06-08T01:47:21.959833+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD17604
  title: 陈庆英藏学文集
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '7991':
      image_group_id: I4PD4591
      title: ''
      total_pages: 544
      order: 1
      base_file: 7991.txt
    C9F7:
      image_group_id: I4PD4592
      title: ''
      total_pages: 748
      order: 2
      base_file: C9F7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
